// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 187132f48ddf0f604882ba8213fe386f)
declare namespace Cloudflare {
	interface Env {
		RESEND_API_KEY: string | undefined;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
